DP-460 Upgrade to PHP 8.1 / Laravel 9
dreamfactorysoftware/dreamfactory-book-v2 pull request #69
Opened 2023-01-31 08:10 UTC by daniilly

2023-02-15 14:05 UTC, alexanderko requested changes

2023-02-15 14:05 UTC, alexanderko commented on content/en/docs/Upgrade to PHP 8.1/_index.md
> +```
Add diff file as an example

2023-02-15 14:05 UTC, alexanderko commented on content/en/docs/Upgrade to PHP 8.1/_index.md
> +If you use a web server also need to work through some steps. For example, with `Nginx` we need to install `php8.1-fpm` and change `php-fpm` configuration file:
Add section header for NGINX related configuration.

2023-02-17 21:38 UTC, alexanderko commented on content/en/docs/Upgrade to PHP 8.1/_index.md
> +In this case use force install: `pecl install -f [extension name]`
```suggestion
In this case use force install: `pecl install -f <extension name>`
```

It 's common for CLI utils to use `[]` for optional arguments and `<>` for required one

2023-02-22 16:21 UTC, daniilly commented on content/en/docs/Installing and Configuring DreamFactory/_index.md
> +| Executable		  | "C:\Program Files\PHP\v7.4\php-cgi.exe"|
@anas-srikou The changes I made in this diff were focused on fixing the layout. This particular section discusses the process of configuring PHP for IIS, using PHP 7.4 as an example. It's worth noting that we didn't write this section, nor did we attempt to configure DreamFactory on IIS.
>In our example, we’re using PHP 7.4.1 (x64).

2023-02-23 12:37 UTC, alexanderko requested changes

2023-02-23 12:37 UTC, alexanderko commented on content/en/docs/Upgrade to PHP 8.1/_index.md
> +odi8
if this is expected output, lets use a comment `#` for it to prevent an error after pasting snippet into terminal.

2023-02-23 12:37 UTC, alexanderko commented on content/en/docs/Upgrade to PHP 8.1/_index.md
> +$ sudo apt install -y unixodbc-dev
Let's mention know working version of unixodbc here.

2023-03-03 02:27 UTC, anas-srikou approved these changes

2023-03-03 04:09 UTC, krishnapriawan approved these changes

2023-03-03 16:16 UTC, merged